version: '3'
volumes:
  postgres: {}
  gemcache: {}
services:
  redis:
    image: redis:4
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: development
      JOB_WORKER_URL: redis://redis:6379
    volumes:
      - .:/my_app
      - gemcache:/gemcache
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: development
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/my_app:cached
      - gemcache:/gemcache
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: development
      JOB_WORKER_URL: redis://redis:6379
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
