version: '3'
volumes:
  postgres: {}
  gemcache: {}
services:
  db:
    image: postgres:10
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: development
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/my_app
      - gemcache:/gemcache
    depends_on:
      - db
    links:
      - db
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: development
      PORT: 3000
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
